excluded_targets:
  - debug
  - release
  - flash_xip
  - flash_xip_release
  - flash_uf2
  - flash_uf2_release
  - sec_core_img
  - sec_core_img_release
  - flash_xip_hybrid
  - flash_xip_hybrid_release

dependency:
  - board_enet_phy