# Copyright (c) 2023-2025 HPMicro
# SPDX-License-Identifier: BSD-3-Clause

excluded_targets:
  - debug
  - release
  - flash_xip_hybrid
  - flash_xip_hybrid_release
  - sec_core_img
  - sec_core_img_release
dependency:
  - enet
  - board_enet_phy
