excluded_targets:
  - debug
  - release
  - flash_uf2
  - flash_uf2_release
  - flash_xip
  - flash_xip_release
  - sec_core_img
  - sec_core_img_release
dependency:
  - lcdc
  - i2s
  - board_audio_out || board_audio_codec
